version: '3.7'
services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: umbrel-chrome
    shm_size: '2gb'
    environment:
      - SE_NODE_SESSION_TIMEOUT=999999
      - SE_NODE_MAX_SESSIONS=1
    ports:
      - "4444:4444"  # Selenium port
      - "7900:7900"  # noVNC port
    restart: unless-stopped