version: '3.7'
services:
  chrome:
    image: kasmweb/chrome:1.13.1
    container_name: umbrel-chrome
    security_opt:
      - seccomp=unconfined
    environment:
      - KASM_USER=admin
      - KASM_PASS=umbrel123
      - VNC_PW=umbrel123
      - STARTUP_URL=https://google.com
      - KASM_VNC_PATH=/
      - KASM_SSL_CERT_TYPE=none
      - KASM_KEYBOARD=en-us-qwerty
    shm_size: '2gb'
    ports:
      - "6901:6901"
      - "6902:6902"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped